extends Node

enum Part { NONE, HEAD, BODY, LEFT_LEG, RIGHT_LEG, LEFT_ARM, RIGHT_ARM }

enum Mech { PLAYER, ENEMY }

enum Minigame { NONE, ENEMY_BULLET, ENEMY_DRILL, PLAYER_BULLET, PLAYER_DRILL }

enum Personality { CHAOS, OPPORTUNISTIC, SPITEFUL }
